//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedditBet.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedditBet.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;title&quot;: &quot;phrases&quot;,
        ///    &quot;description&quot;: &quot;A list of key phrases the bot can search for&quot;,
        ///    &quot;phrases&quot;: [
        ///        // Summoners
        ///
        ///        &quot;/u/cfb_betbot&quot;,
        ///        &quot;cfb_betbot&quot;,
        ///        &quot;aksdxxpLllsfo9 zidjl&quot;, // For testing
        ///
        ///        // Key/Target Phrases
        ///
        ///        &quot;If ... win, I&apos;ll&quot;,
        ///        &quot;If ... lose, I&apos;ll&quot;,
        ///        &quot;If ... win, you have to&quot;,
        ///        &quot;If ... lose, you have to&quot;,
        ///        &quot;Anybody wanna bet&quot;,
        ///        &quot;be willing to bet&quot;,
        ///        &quot;bet ... if ... wins&quot;,
        ///        &quot;bet ... i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phrases {
            get {
                return ResourceManager.GetString("phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This is a header
        ///
        ///Hello, world!
        ///
        ///* Foo
        ///* Bar
        ///* Baz
        ///
        ///&gt; This is a blockquote
        ///&gt; Simple.
        ///  
        ///    This is a code block
        ///    See?
        ///
        ///%link01%
        ///
        ///End of message..
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
